### PR TITLE
Features and bug fixes

### PR DESCRIPTION
**Pull request by jriyyya**
### [Fixed highscore loading, now shows updated highscore at game_over screen](https://github.com/sugarlabs/classify-cats/commit/c1f37a3d3d77f38374b4c50e7c1d5a87330b5741)
This commit aims to fix the issue with how the highscore is loaded which doesn't let it update in contrast to the current score 
This buggy behavior is shown in the below screenshot and has been fixed by this commit.

Screenshot 2023-02-17 152841

### [Added showing current score after every game, and a bonus score for t…](https://github.com/sugarlabs/classify-cats/commit/08ae06724e59619f72f83e1cd1c393175b332fbb)
This commit adds a message to the end screen of each screen, the current score is displayed at the end of every game now. 
Also in the ```Rows``` game mode, there was no reward for the reaction time of correctly selecting the cats before the time was over
So I have added bonus score for answering correctly by adding the remaining time to the player's score.

image

### [Fixed grammatical errors in messages](https://github.com/sugarlabs/classify-cats/commit/784d7e637f63c2b919c4a00911c9a4e256309a80)
Fixed a few grammatical errors in the messages displayed in game

### [fixed the win check for placing cats - based on type instead of count…](https://github.com/sugarlabs/classify-cats/commit/d43dbab52f288544c8788b9a11fa1d05027d584f)

This aims to fix the win check condition of the `DIVIDED_SCREEN` game mode.
The game was intended to check if the cats with even no of the same cats were on one side of the screen
for eg: place all green cats on the left of the screen if the total count of green cats is even
and so on
but the check was for if on the left side of the screen there were even no of cats regardless of their type and odd count on the right. This has been changed by this commit
This commit finally fixed how the game checks the win condition

### CODE REVIEW

**Comment by jriyyya** [comment]
Hi @quozl, Can you please review this.

**Comment by quozl** [comment]
The commit messages were difficult to understand.  Please follow the Making Commits section of our contributors guide when writing the commit message.

https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits

**Comment by quozl** [comment]
Also, a reminder that the pull request message is not kept, and does not need to form part of the effort.  The pull request message can be very small, because the commit messages should explain everything.

As git commit messages don't contain images yet, they should describe any visual problems or changes as text.

**Comment by jriyyya** [comment]
> The commit messages were difficult to understand.  Please follow the Making Commits section of our contributors guide when writing the commit message.
> 
> https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits

I guess I am missing something, Can you tell me what could have been a better commit message for any of the changes I did so that I can get a better understanding. :')

**Comment by quozl** [comment]
A one line introduction followed by a blank line and more lines if necessary.  A line is text up to a new line mark.  Try to have the lines limited to 80 characters, so that viewing the commit can work at the command line in a typical 80 column terminal window.

Imperative mood; fixed should be fix, added should be add.

Make sure any explanation that you make is in the commit message.  For example in https://github.com/sugarlabs/classify-cats/pull/6/commits/d43dbab52f288544c8788b9a11fa1d05027d584f you supply an extensive text explanation in the pull request but not in the commit message.

**Comment by jriyyya** [comment]
Thanks, Will keep these things in mind.

**Pull request merged**
