### PR TITLE
Add game instructions & help button

### LINKED ISSUE #8: Add help instructions
It's difficult to know how the activity works at first so we need a help button.

@jriyyya wanna take this?

### PR DESCRIPTION
**Pull request by ghost**
* Provided concise instructions for three game types.
* Implemented a help button for player guidance.

This closes https://github.com/sugarlabs/classify-cats/issues/8

Kindly review @walterbender @chimosky @quozl .

### CODE REVIEW

**Comment by ghost** [comment]
Made the instruction more clear and informative and also made it based on level name that for what level what has to be done.
Thanks kindly see.

**Comment by ghost** [comment]
Fixed the flake8 that were generated due long lines in the pr.

**Review by chimosky — COMMENTED** [review]
`gamehelp` and `helpbutton` can be one file.

**Comment by ghost** [comment]
I'm unsure if merging the files is the right choice because `helpbutton.py` is copied and has a different author (mentioned in the file), while `gamehelp.py` is the file I wrote. I'd prefer to keep them separate.
I have credited the author in commit message also.

**Comment by chimosky** [comment]
> I'm unsure if merging the files is the right choice because `helpbutton.py` is copied and has a different author (mentioned in the file), while `gamehelp.py` is the file I wrote. I'd prefer to keep them separate. I have credited the author in commit message also.

The license gives you the ability to modify the code and share, which is what you've done and that's not an issue, you can claim a copyright on your changes if you want.

Merging the files make sense as one imports the other and they both share a common goal, so no need to keep them separate.

**Comment by ghost** [comment]
Merged Files!

**Comment by chimosky** [comment]
Tested 4e7f6ce, you should drop the numbers in the help message.

**Comment by ghost** [comment]
Yes, there seem to some problem with wordings as well I think its not clear enough.
Thanks.

**Pull request closed without merging**
