### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by Abhay-dot**

### CODE REVIEW

**Comment by Abhay-dot** [comment]
Hopefully this is better, i tested it out and it exited the logs with 0 status. (Port to Python3)

**Comment by chimosky** [comment]
Tested, you haven't made sure of interger divisions; that values are what they should be. 
Can you make sure of that?

**Comment by Abhay-dot** [comment]
what do you mean?

**Comment by chimosky** [comment]
You've left interger divisions unchanged, and in python3 interger division is done with `//`. 
There could be change in values you're expecting.

**Comment by Abhay-dot** [comment]
ohhhh, thanks for the help

**Comment by Abhay-dot** [comment]
I'll do it right away

**Comment by quozl** [comment]
Thanks.  Reviewed.  Please show how you did the test?  I have time to test on Monday.

In 98fad73, it looks like you may have changed every division; while this is functionally correct, it may not be necessary to change every division, and is unusual.  Not this time, but in future, the way to identify divisions that must be changed;
* if the result is used as an index,
* if the result is immediately coerced to an integer,
* if the inputs to the division are always integers in Python 2 and Python 3 (observed by using Pdb or debug prints).

**Comment by Abhay-dot** [comment]
ok ill do those changes too

**Comment by Abhay-dot** [comment]
Screen Shot 2020-01-18 at 12 20 33

**Comment by Abhay-dot** [comment]
Can you also give me an example where there is an unnecessary division change, cause i can't find any.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Thanks for the test results; but your logs show an error.  Is this error caused by your change?

**Comment by Abhay-dot** [comment]
no, its not

**Comment by quozl** [comment]
Thanks.  Please raise it as an issue in this repository.  I can't copy and paste from your screenshot.  Please use text copy and paste into the issue, don't use the screenshot.  We can't search screenshots.

**Comment by Abhay-dot** [comment]
ok, and will i bee done after that?

**Comment by quozl** [comment]
Probably, yes.  This is not a critical repository for me.  Your test results look adequate apart from the traceback, which you can raise as an issue or you could fix it.  I guessed you didn't want to fix it, because you had not.

**Comment by Abhay-dot** [comment]
Hey.
	Sorry for the late response, i just reached home and opened an issue.

**Pull request merged**
